spring:
  application:
    name: literalura
  datasource:
    url: jdbc:postgresql://localhost:5432/test_database
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update